### ISSUE TITLE
Local Testing

### ISSUE THREAD

**Issue by MarkHerhold** [cbschuld/rds-data#5]
Hey @cbschuld ,

I'm giving this a try and found that I need to be able to pass options ([see constructor, types](https://github.com/aws/aws-sdk-js/blob/eb3450b6cc4393de8a41db325d0562b7df9fad3e/clients/rdsdataservice.d.ts#L12-L13)) to the underlying RDSDataService API for local testing.

For example, here's my ideal config:

```js
const isCI = process.env['CI'] === 'true';

export const db = new RDSDatabase({
    region: 'us-east-1',
    secretArn: process.env['SECRET_ARN']!,
    resourceArn: process.env['CLUSTER_ARN']!,
    database: process.env['DB_NAME']!,
    options: isCI
        ? {
              // we're in a test environment
              endpoint: new AWS.Endpoint('http://127.0.0.1:8080'),
              httpOptions: {
                  agent: new http.Agent(),
              },
          }
        : {
              // not in a test environment
          },
});
```

I'm using [`koxudaxi/local-data-api`](https://github.com/koxudaxi/local-data-api) for local testing.

Any thoughts on this? Do you do local testing (local stack or a stack in CI), but with a different approach?

**Comment by MarkHerhold** [comment]
I potentially have a solution for this (need to PR).

**Comment by cbschuld** [comment]
@MarkHerhold awesome!  Right now I have only been testing using a serverless offline but still hitting the production RDS API.

**Comment by MarkHerhold** [comment]
@cbschuld How do you feel about using GitHub actions to run some local tests? Now that I'm a collaborator I could add that pretty easily if you like.

**Comment by cbschuld** [comment]
sounds great @MarkHerhold

**Comment by cbschuld** [comment]
@MarkHerhold I believe you work takes care of this!  Thx again!
